### ISSUE TITLE
switch from debian package dnsmasq to dnsmasq-base

### ISSUE THREAD

**Issue by txt-file** [FreifunkVogtland/ansible-config#2]
The dnsmasq package brings mainly the sysVinit / systemd scripts and a default config file.[0] If you start/run dnsmasq via own scripts then you have no need for the dnsmasq package.

As I see it:
* you use an own config file
* you start dnsmasq via own methods (cron)

Therefore I do not see any use for the dnsmasq package and recommend to switch to the dnsmasq-base package.

[0] https://packages.debian.org/sid/all/dnsmasq/filelist

**Comment by ecsv** [comment]
We use the dnsmasq's systemd files and not via our own scripts
